server:
  port: 8081

spring:
  security:
    basic:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5431/user-roles-auth
    username: useradmin
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
